name: Automatic release

on:
  workflow_dispatch:
  push:
    branches:
      - 'v1.18.x'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: "semantic-release @semantic-release/exec conventional-changelog-conventionalcommits"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get java version
        if: steps.semantic.outputs.new_release_published == 'true'
        id: java_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'java_version'

      - name: Set up JDK
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ steps.java_version.outputs.value }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        if: steps.semantic.outputs.new_release_published == 'true'
        run: chmod +x gradlew

      - name: Setup forge mdk
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./gradlew init

      - name: Datagen before build
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./gradlew runData

      - name: Build with Gradle
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./gradlew build

      - name: Generate changelog value
        shell: bash
        id: release_description
        run: |
          description="${{ steps.semantic.outputs.new_release_notes }}"
          description="${description//'%'/'\n'}"
          description="${description//$'\n'/'\n'}"
          description="${description//$'\r'/'\n'}"
          echo $description
          echo "::set-output name=description::$description"

      - name: Get minecraft version
        if: steps.semantic.outputs.new_release_published == 'true'
        id: mc_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mc_version'

      - name: Send Discord alert
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: Sniddl/discord-commits@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          last-commit-only: true
          message: "New experimental version released!"
          embed: |
            {
            "title": "Version ${{ steps.semantic.outputs.new_release_version }} for ${{ steps.mc_version.outputs.value }}",
            "description": "Changes:\n```${{ steps.release_description.outputs.description }}\n```",
            "footer":
              {
                "text": "⚠️ This is an automatically generated file with untested content. Be extremely careful not to use this in your main world without creating backups! ⚠️"
              }
            }

      - name: Discord early access publish
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: build/libs/*${{ steps.semantic.outputs.new_release_version }}.jar